version: '3'
services:
  python_api:
    container_name: python_api
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    ports:
      - "5000:5000"
    volumes:
      - .:/project
