name: Release

on: [workflow_dispatch]

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bump version and create changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
